import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono, Nunito_Sans, Quicksand, Barlow, Raleway } from "next/font/google";
import "./globals.css";

// Keep every cacheable page in the Next.js/ISR cache for one year.
// The literal value is required so Next.js can analyze it at build time.
export const revalidate = 31536000;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: "100"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nunitoSans.variable} ${dmSans.variable} ${raleway.variable} ${quicksand.variable} ${barlow.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
